'use strict'

/** @type {import('@adonisjs/lucid/src/Schema')} */
const Schema = use('Schema')

class CreateTblTarjetaFamiliarSchema extends Schema {
  up () {
    this.create('tbl_tarjetas_familiares', (table) => {
      table.increments()
      table.string('codigo').nullable()
      table.string('ficha').nullable()
      table.string('nivel').nullable()
      table.string('puntaje').nullable()
      table.boolean('pacienteportabilidad').nullable()
      table.boolean('pacientecambiodomicilio').nullable()
      table.string('zona').nullable()
      table.string('departamento_id').nullable()
      table.string('municipio_id').nullable()
      table.string('corregimiento_id').nullable()
      table.string('vereda_id').nullable()
      table.string('telefono').nullable()
      table.string('direccion').nullable()
      table.date('fechaproximavisita').nullable()
      table.double('longitud').nullable()
      table.double('latitud').nullable()
      table.double('exactitud').nullable()
      table.string('gatos').nullable()
      table.integer('gatos_cuantos').nullable()
      table.integer('gatos_vacunados').nullable()
      table.string('gatos_trivalente').nullable()
      table.string('gatos_refuerzo_trivalente').nullable()
      table.string('gatos_rabia').nullable()
      table.string('gatos_presenta_carnet').nullable()
      table.string('perros').nullable()
      table.string('perros_cuantos').nullable()
      table.string('perros_vacunados').nullable()
      table.string('perros_parvo_moquillo').nullable()
      table.string('perros_polivalente').nullable()
      table.string('perros_rabia').nullable()
      table.string('perros_presenta_carnet').nullable()
      table.string('equinos').nullable()
      table.string('equinos_cuantos').nullable()
      table.string('equinos_vacunados').nullable()
      table.string('equinos_encefalomielitis').nullable()
      table.string('equinos_influenza').nullable()
      table.string('equinos_presenta_carnet').nullable()
      table.string('otros').nullable()
      table.string('otros_cuantos').nullable()
      table.string('otros_vacunados').nullable()
      table.string('donde_toma_agua').nullable()
      table.string('la_basura_es').nullable()
      table.boolean('iluminacion_adecuada').nullable()
      table.boolean('ventilacion_adecuada').nullable()
      table.boolean('roedores').nullable()
      table.boolean('reservorios_de_agua').nullable()
      table.boolean('anjeos_puertas_y_ventanas').nullable()
      table.boolean('uso_de_toldillos').nullable()
      table.boolean('material_predominante_en_piso_techo_paredes').nullable()
      table.boolean('con_letrina_pero_alguien_no_la_usa').nullable()
      table.boolean('plagas').nullable()
      table.boolean('convivencia_inadecuada_con_animales').nullable()
      table.boolean('mala_disposicion_de_plaguicidas').nullable()
      table.boolean('contaminacion_del_agua').nullable()
      table.boolean('accidentes_ofidico').nullable()
      table.boolean('usan_plaguicidas').nullable()
      table.boolean('no_siempre_hierve_el_agua').nullable()
      table.boolean('areas_endemicas_de_enfermedades_de_salud_publica').nullable()
      table.boolean('mala_higiene_en_preparacion_de_alimentos').nullable()
      table.boolean('piojos').nullable()
      table.boolean('parasitos').nullable()
      table.boolean('acaros').nullable()
      table.boolean('zancudos').nullable()    
      table.timestamps()
    })
  }

  down () {
    this.drop('tbl_tarjetas_familiares')
  }
}

module.exports = CreateTblTarjetaFamiliarSchema
