'use strict'

const Schema = use('Schema')

class AddNewColumnsToSchema extends Schema {
  up () {
    this.table('tbl_registros_personales', (table) => {
      table.string('razon_social_ips').nullable()
      table.string('lengua_propia').nullable()
      table.string('tipo_ocupacion').nullable()
      table.string('salud_mental').nullable()
      table.string('conocimiento_salud').nullable()
      table.string('poblacion_vulnerable').nullable()
      table.string('tipo_discapacidad').nullable()
      table.boolean('tiene_cuidador').nullable()
      table.string('descapacidad_registro_localizacion_caracteri').nullable()
      table.boolean('presento_tos_expectoracion').nullable()
      table.boolean('fuma').nullable()
      table.string('hace_cuanto').nullable()
      table.integer('cuantos_cigarrillos_diarios').nullable()
      table.boolean('expocicion_quimicos').nullable()
      table.boolean('expocicion_convulsivos').nullable()
      table.string('religion').nullable()
      table.boolean('consumo_alcohol').nullable()
      table.string('frecuancia_consumo_alcohol').nullable()
      table.string('hace_cuanto_alcohol').nullable()
      table.boolean('consumo_sustan_psicoactivas').nullable()
      table.string('sustan_psicoactivas').nullable()
      table.string('frecuensia_sustan_psicoactivas').nullable()
      table.string('hace_cuanto_sustan_psicoactivas').nullable()
      table.boolean('planificacion_familiar').nullable()
      table.date('fecha_ultima_citologia').nullable()
      table.date('fecha_ultima_mestruacion').nullable()
      table.boolean('sufre_enf_cronica').nullable()
      table.string('patologias').nullable()
      table.string('alimientacion_lactancia').nullable()
      table.boolean('frecu_sepillado').nullable()
      table.boolean('utiliza_crema_dental').nullable()
      table.boolean('ingesta_crema_dental').nullable()
    })
  }

  down () {
    this.table('tbl_registros_personales', (table) => {
      table.dropColumn('razon_social_ips')
      table.dropColumn('lengua_propia')
      table.dropColumn('tipo_ocupacion')
      table.dropColumn('salud_mental')
      table.dropColumn('conocimiento_salud')
      table.dropColumn('poblacion_vulnerable')
      table.dropColumn('tipo_discapacidad')
      table.dropColumn('tiene_cuidador')
      table.dropColumn('descapacidad_registro_localizacion_caracteri')
      table.dropColumn('presento_tos_expectoracion')
      table.dropColumn('fuma')
      table.dropColumn('hace_cuanto')
      table.dropColumn('cuantos_cigarrillos_diarios')
      table.dropColumn('expocicion_quimicos')
      table.dropColumn('expocicion_convulsivos')
      table.dropColumn('religion')
      table.dropColumn('consumo_alcohol')
      table.dropColumn('frecuancia_consumo_alcohol')
      table.dropColumn('hace_cuanto_alcohol')
      table.dropColumn('consumo_sustan_psicoactivas')
      table.dropColumn('sustan_psicoactivas')
      table.dropColumn('frecuensia_sustan_psicoactivas')
      table.dropColumn('hace_cuanto_sustan_psicoactivas')
      table.dropColumn('planificacion_familiar')
      table.dropColumn('fecha_ultima_citologia')
      table.dropColumn('fecha_ultima_mestruacion')
      table.dropColumn('sufre_enf_cronica')
      table.dropColumn('patologias')
      table.dropColumn('alimientacion_lactancia')
      table.dropColumn('frecu_sepillado')
      table.dropColumn('utiliza_crema_dental')
      table.dropColumn('ingesta_crema_dental')
    })
  }
}

module.exports = AddNewColumnsToSchema
