'use strict'

/** @type {import('@adonisjs/lucid/src/Schema')} */
const Schema = use('Schema')

class AddNewColumnsToSchema extends Schema {
  up () {
    this.table('tbl_tarjetas_familiares', (table) => {
      table.integer('ingresos_mensuales_vivienda').nullable()
      table.boolean('alcantarillado').nullable()
      table.boolean('gas').nullable()
      table.string('actividad_economica', 255).nullable()
      table.string('anos_construccion', 255).nullable()
      table.string('iluminacion_interior', 255).nullable()
      table.string('humo_interior', 255).nullable()
      table.string('tratamiento_agua', 255).nullable()
      table.string('que_hace_res_organicos', 255).nullable()
      table.string('que_hace_res_peligrosos', 255).nullable()
      table.boolean('moscas').nullable()
      table.boolean('pulgas').nullable()
      table.boolean('garrapatas').nullable()
      table.boolean('cinches').nullable()
      table.boolean('niguas').nullable()
      table.string('control_vectores', 255).nullable()
      table.boolean('realizo_control_vectores_institucion').nullable()
      table.string('focos_contaminacion', 255).nullable()
      table.boolean('carroneros_serca_vivienda').nullable()
      table.string('afectaciones_externas', 255).nullable()
      table.string('observa_afectacion', 255).nullable()
      table.boolean('kiosko_digital').nullable()
      table.boolean('zonas_deportivas').nullable()
      table.boolean('parque_recreativo').nullable()
      table.boolean('gimnasio').nullable()
      table.boolean('salon_comunal').nullable()
      table.boolean('escuela').nullable()
      table.boolean('colegio').nullable()
      table.boolean('iglesia').nullable()
      table.boolean('polideportivo').nullable()
      table.boolean('escuela_deportiva').nullable()
      table.boolean('escuela_cultural').nullable()
      table.boolean('senal_radio').nullable()
      table.boolean('senal_tv').nullable()
      table.boolean('telefonia_fija').nullable()
      table.boolean('telefonia_celular').nullable()
      table.boolean('internet').nullable()
      table.boolean('computador').nullable()
      table.boolean('celular').nullable()
      table.boolean('tablet').nullable()
      table.boolean('telivisor').nullable()
      table.boolean('radio').nullable()
      table.boolean('videojuegos').nullable()
      table.string('tipo_via', 255).nullable()
      table.string('consumo_fruta_verdura', 255).nullable()
      table.string('consumo_proteina', 255).nullable()
      table.string('porque_noconsume', 255).nullable()
      table.boolean('tien_huerta').nullable()
      table.string('frutas', 255).nullable()
      table.string('verduras_hotalizas', 255).nullable()
      table.string('raices_tuberculos', 255).nullable()
      table.string('leguminozas', 255).nullable()
      table.boolean('tien_animales_consumo').nullable()
      table.boolean('aves').nullable()
      table.boolean('peces').nullable()
      table.boolean('vacas').nullable()
      table.boolean('porcinos').nullable()
      table.boolean('ovinos').nullable()
      table.boolean('curies_conejos').nullable()
      table.integer('habitantes').nullable()
      table.integer('ingresos_habitantes').nullable()
      table.string('clasificacion_pobreza', 255).nullable()
      table.string('proyecto_vivienda', 255).nullable()
      table.string('clasificacion_riesgo_vivienda', 255).nullable()
      table.string('clasificacion_saneamiento', 255).nullable()
    })
  }

  down () {
    this.table('tbl_tarjetas_familiares', (table) => {
      table.dropColumn('ingresos_mensuales_vivienda')
      table.dropColumn('alcantarillado')
      table.dropColumn('gas')
      table.dropColumn('actividad_economica')
      table.dropColumn('anos_construccion')
      table.dropColumn('iluminacion_interior')
      table.dropColumn('humo_interior')
      table.dropColumn('tratamiento_agua')
      table.dropColumn('que_hace_res_organicos')
      table.dropColumn('que_hace_res_peligrosos')
      table.dropColumn('moscas')
      table.dropColumn('pulgas')
      table.dropColumn('garrapatas')
      table.dropColumn('cinches')
      table.dropColumn('niguas')
      table.dropColumn('control_vectores')
      table.dropColumn('realizo_control_vectores_institucion')
      table.dropColumn('focos_contaminacion')
      table.dropColumn('carroneros_serca_vivienda')
      table.dropColumn('afectaciones_externas')
      table.dropColumn('observa_afectacion')
      table.dropColumn('kiosko_digital')
      table.dropColumn('zonas_deportivas')
      table.dropColumn('parque_recreativo')
      table.dropColumn('gimnasio')
      table.dropColumn('salon_comunal')
      table.dropColumn('escuela')
      table.dropColumn('colegio')
      table.dropColumn('iglesia')
      table.dropColumn('polideportivo')
      table.dropColumn('escuela_deportiva')
      table.dropColumn('escuela_cultural')
      table.dropColumn('senal_radio')
      table.dropColumn('senal_tv')
      table.dropColumn('telefonia_fija')
      table.dropColumn('telefonia_celular')
      table.dropColumn('internet')
      table.dropColumn('computador')
      table.dropColumn('celular')
      table.dropColumn('tablet')
      table.dropColumn('telivisor')
      table.dropColumn('radio')
      table.dropColumn('videojuegos')
      table.dropColumn('tipo_via')
      table.dropColumn('consumo_fruta_verdura')
      table.dropColumn('consumo_proteina')
      table.dropColumn('porque_noconsume')
      table.dropColumn('tien_huerta')
      table.dropColumn('frutas')
      table.dropColumn('verduras_hotalizas')
      table.dropColumn('raices_tuberculos')
      table.dropColumn('leguminozas')
      table.dropColumn('tien_animales_consumo')
      table.dropColumn('aves')
      table.dropColumn('peces')
      table.dropColumn('vacas')
      table.dropColumn('porcinos')
      table.dropColumn('ovinos')
      table.dropColumn('curies_conejos')
      table.dropColumn('habitantes')
      table.dropColumn('ingresos_habitantes')
      table.dropColumn('clasificacion_pobreza')
      table.dropColumn('proyecto_vivienda')
      table.dropColumn('clasificacion_riesgo_vivienda')
      table.dropColumn('clasificacion_saneamiento')
    })
  }
}

module.exports = AddNewColumnsToSchema
